http://localhost:3000/api/test/2?debug=true

###

http://localhost:3000/hello

###

POST http://localhost:3000/api/ping
Content-Type: application/json

{ "message": "test" }

###

POST http://localhost:3000/api/ping
Content-Type: application/x-www-form-urlencoded

message=test

###

http://localhost:3000/api/version


