// Test routing and query params
http://localhost:3000/api/test/2?debug=true

###

// Test mock verb discrimination
http://localhost:3000/hello

###

// Test fallback mock with no verb specified
POST http://localhost:3000/hello

###

// Test post
POST http://localhost:3000/api/ping
Content-Type: application/json

{ "message": "test" }

###

// Test post with different content-type
POST http://localhost:3000/api/ping
Content-Type: application/x-www-form-urlencoded

message=test

###

// Test simple template with optional query param
http://localhost:3000/api/version

###

// Test 404
http://localhost:3000/notFound

###

// Discriminate 404 by accept header
http://localhost:3000/
Accept: text/plain

###

// Defeat Node cache for JS mocks
http://localhost:3000/api/random

