// ---------------------------------------------------------------------------
// Install REST Client extension for VS Code to use this file:
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// ---------------------------------------------------------------------------

// Test routing and query params
http://localhost:3000/api/test/2?debug=true

###

// Test mock verb discrimination
http://localhost:3000/api/hello

###

// Test fallback mock with no verb specified
POST http://localhost:3000/api/hello

###

// Test post
POST http://localhost:3000/api/ping
Content-Type: application/json

{ "message": "test" }

###

// Test post with different content-type
POST http://localhost:3000/api/ping
Content-Type: application/x-www-form-urlencoded

message=test

###

// Test multiple methods support
PUT http://localhost:3000/api/ping
Content-Type: application/json

{ "message": "test" }

###

// Test template match either based on path or file name
http://localhost:3000/api/version

###

// Test 404
http://localhost:3000/notFound

###

// Discriminate 404 by accept header
http://localhost:3000/
Accept: application/json

###

// Defeat Node cache for JS mocks
http://localhost:3000/api/random

###

// Match any type
http://localhost:3000/api/text

###

// Match only specified type
http://localhost:3000/api/text
Accept: text/*

###

// Test template with JS evaluation
 http://localhost:3000/headers

###

// JS mock with custom status and headers
http://localhost:3000/user-agent

###

// Test JSON array
http://localhost:3000/api/quotes
